/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddIcons: typeof import('./src/components/icons/AddIcons.vue')['default']
    AnnouncementsBlock: typeof import('./src/components/announcements/AnnouncementsBlock.vue')['default']
    AnnouncementsBlocks: typeof import('./src/components/announcements/AnnouncementsBlocks.vue')['default']
    BaseLayout: typeof import('./src/components/base/BaseLayout.vue')['default']
    IonAvatar: typeof import('@ionic/vue')['IonAvatar']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonBadge: typeof import('@ionic/vue')['IonBadge']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardContent: typeof import('@ionic/vue')['IonCardContent']
    IonCardHeader: typeof import('@ionic/vue')['IonCardHeader']
    IonCardSubtitle: typeof import('@ionic/vue')['IonCardSubtitle']
    IonCardTitle: typeof import('@ionic/vue')['IonCardTitle']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonFooter: typeof import('@ionic/vue')['IonFooter']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonImg: typeof import('@ionic/vue')['IonImg']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    IonText: typeof import('@ionic/vue')['IonText']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    MainLayout: typeof import('./src/components/base/MainLayout.vue')['default']
    PeopleList: typeof import('./src/components/people/PeopleList.vue')['default']
    PeopleListItem: typeof import('./src/components/people/PeopleListItem.vue')['default']
    PersonModal: typeof import('./src/components/people/PersonModal.vue')['default']
    PresentationBlock: typeof import('./src/components/presentations/PresentationBlock.vue')['default']
    PresentationBlocks: typeof import('./src/components/presentations/PresentationBlocks.vue')['default']
    PresentationItem: typeof import('./src/components/presentations/PresentationItem.vue')['default']
    QuestionsExample: typeof import('./src/components/questions/QuestionsExample.vue')['default']
    QuestionsFooterSendQuestion: typeof import('./src/components/questions/QuestionsFooterSendQuestion.vue')['default']
    QuestionsList: typeof import('./src/components/questions/QuestionsList.vue')['default']
    QuestionsListItem: typeof import('./src/components/questions/QuestionsListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
