version: '3.8'

services:
  app:
    build:
      context: .
      target: app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/conference_db
    depends_on:
      - db
    volumes:
      - ./prisma:/app/prisma
    command: sh -c "npx prisma migrate deploy && npm start"

  frontend:
    build:
      context: .
      target: nginx
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=conference_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 