services:
  - type: web
    name: conference-app
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: conference-db
          property: connectionString
      - key: VITE_API_BASE
        value: /server
      - key: PORT
        value: 80
      - key: INITIAL_MIGRATION
        value: true
      - key: ADMIN_PASSWORD
        sync: false
        required: true
        description: Admin password
    buildFilter:
      paths:
        - src/**/*
        - public/**/*
        - package*.json
        - vite.config.ts
        - tsconfig.json
        - Dockerfile
        - nginx.conf
        - supervisord.conf
        - prisma/**/*
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: conference-db
    databaseName: conference
    plan: free
    ipAllowList: [] 