services:
  - type: web
    name: conference-app
    runtime: docker
    plan: starter
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: conference-db
          property: connectionString
      - key: VITE_API_BASE
        value: https://${SERVICE_NAME}.onrender.com/server
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

databases:
  - name: conference-db
    databaseName: conference
    plan: starter
    ipAllowList: []
    migrations:
      - type: prisma
        command: npx prisma migrate deploy 